{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2019-3498",
		"assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
		"assignerShortName": "mitre",
		"state": "PUBLISHED",
		"datePublished": "2019-01-09T22:00:00",
		"dateUpdated": "2024-08-04T19:12:09.465Z",
		"dateReserved": "2019-01-01T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
				"shortName": "mitre",
				"dateUpdated": "2019-03-20T22:06:03"
			},
			"descriptions": [
				{
					"lang": "en",
					"value": "In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in django.views.defaults.page_not_found(), leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content."
				}
			],
			"affected": [
				{
					"vendor": "n/a",
					"product": "n/a",
					"versions": [
						{
							"status": "affected",
							"version": "n/a"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "text",
							"lang": "en",
							"description": "n/a"
						}
					]
				}
			],
			"references": [
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://groups.google.com/forum/#%21topic/django-announce/VYU7xQQTEPQ"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://docs.djangoproject.com/en/dev/releases/security/"
				},
				{
					"name": "USN-3851-1",
					"tags": [
						"vendor-advisory",
						"x_refsource_UBUNTU"
					],
					"url": "https://usn.ubuntu.com/3851-1/"
				},
				{
					"name": "106453",
					"tags": [
						"vdb-entry",
						"x_refsource_BID"
					],
					"url": "http://www.securityfocus.com/bid/106453"
				},
				{
					"name": "[debian-lts-announce] 20190106 [SECURITY] [DLA 1629-1] python-django security update",
					"tags": [
						"mailing-list",
						"x_refsource_MLIST"
					],
					"url": "https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://www.djangoproject.com/weblog/2019/jan/04/security-releases/"
				},
				{
					"name": "DSA-4363",
					"tags": [
						"vendor-advisory",
						"x_refsource_DEBIAN"
					],
					"url": "https://www.debian.org/security/2019/dsa-4363"
				},
				{
					"name": "FEDORA-2019-5ad2149e99",
					"tags": [
						"vendor-advisory",
						"x_refsource_FEDORA"
					],
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/"
				}
			],
			"datePublic": "2019-01-09T00:00:00",
			"x_legacyV4Record": {
				"CVE_data_meta": {
					"ASSIGNER": "cve@mitre.org",
					"ID": "CVE-2019-3498",
					"STATE": "PUBLIC"
				},
				"affects": {
					"vendor": {
						"vendor_data": [
							{
								"product": {
									"product_data": [
										{
											"product_name": "n/a",
											"version": {
												"version_data": [
													{
														"version_value": "n/a"
													}
												]
											}
										}
									]
								},
								"vendor_name": "n/a"
							}
						]
					}
				},
				"data_format": "MITRE",
				"data_type": "CVE",
				"data_version": "4.0",
				"description": {
					"description_data": [
						{
							"lang": "eng",
							"value": "In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in django.views.defaults.page_not_found(), leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content."
						}
					]
				},
				"problemtype": {
					"problemtype_data": [
						{
							"description": [
								{
									"lang": "eng",
									"value": "n/a"
								}
							]
						}
					]
				},
				"references": {
					"reference_data": [
						{
							"name": "https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ",
							"refsource": "MISC",
							"url": "https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ"
						},
						{
							"name": "https://docs.djangoproject.com/en/dev/releases/security/",
							"refsource": "MISC",
							"url": "https://docs.djangoproject.com/en/dev/releases/security/"
						},
						{
							"name": "USN-3851-1",
							"refsource": "UBUNTU",
							"url": "https://usn.ubuntu.com/3851-1/"
						},
						{
							"name": "106453",
							"refsource": "BID",
							"url": "http://www.securityfocus.com/bid/106453"
						},
						{
							"name": "[debian-lts-announce] 20190106 [SECURITY] [DLA 1629-1] python-django security update",
							"refsource": "MLIST",
							"url": "https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html"
						},
						{
							"name": "https://www.djangoproject.com/weblog/2019/jan/04/security-releases/",
							"refsource": "MISC",
							"url": "https://www.djangoproject.com/weblog/2019/jan/04/security-releases/"
						},
						{
							"name": "DSA-4363",
							"refsource": "DEBIAN",
							"url": "https://www.debian.org/security/2019/dsa-4363"
						},
						{
							"name": "FEDORA-2019-5ad2149e99",
							"refsource": "FEDORA",
							"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/"
						}
					]
				}
			}
		},
		"adp": [
			{
				"providerMetadata": {
					"orgID": "af854a3a-2127-422b-91ae-364da2661108",
					"shortName": "CVE",
					"dateUpdated": "2024-08-04T19:12:09.465Z"
				},
				"title": "CVE Program Container",
				"references": [
					{
						"tags": [
							"x_refsource_MISC",
							"x_transferred"
						],
						"url": "https://groups.google.com/forum/#%21topic/django-announce/VYU7xQQTEPQ"
					},
					{
						"tags": [
							"x_refsource_MISC",
							"x_transferred"
						],
						"url": "https://docs.djangoproject.com/en/dev/releases/security/"
					},
					{
						"name": "USN-3851-1",
						"tags": [
							"vendor-advisory",
							"x_refsource_UBUNTU",
							"x_transferred"
						],
						"url": "https://usn.ubuntu.com/3851-1/"
					},
					{
						"name": "106453",
						"tags": [
							"vdb-entry",
							"x_refsource_BID",
							"x_transferred"
						],
						"url": "http://www.securityfocus.com/bid/106453"
					},
					{
						"name": "[debian-lts-announce] 20190106 [SECURITY] [DLA 1629-1] python-django security update",
						"tags": [
							"mailing-list",
							"x_refsource_MLIST",
							"x_transferred"
						],
						"url": "https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html"
					},
					{
						"tags": [
							"x_refsource_MISC",
							"x_transferred"
						],
						"url": "https://www.djangoproject.com/weblog/2019/jan/04/security-releases/"
					},
					{
						"name": "DSA-4363",
						"tags": [
							"vendor-advisory",
							"x_refsource_DEBIAN",
							"x_transferred"
						],
						"url": "https://www.debian.org/security/2019/dsa-4363"
					},
					{
						"name": "FEDORA-2019-5ad2149e99",
						"tags": [
							"vendor-advisory",
							"x_refsource_FEDORA",
							"x_transferred"
						],
						"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/"
					}
				]
			}
		]
	}
}
