{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2020-15163",
		"assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
		"assignerShortName": "GitHub_M",
		"state": "PUBLISHED",
		"datePublished": "2020-09-09T17:30:19",
		"dateUpdated": "2024-08-04T13:08:22.456Z",
		"dateReserved": "2020-06-25T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "a0819718-46f1-4df5-94e2-005712e83aaa",
				"shortName": "GitHub_M",
				"dateUpdated": "2020-09-09T17:30:19"
			},
			"title": "Invalid root may become trusted root in The Update Framework (TUF)",
			"descriptions": [
				{
					"lang": "en",
					"value": "Python TUF (The Update Framework) reference implementation before version 0.12 it will incorrectly trust a previously downloaded root metadata file which failed verification at download time. This allows an attacker who is able to serve multiple new versions of root metadata (i.e. by a person-in-the-middle attack) culminating in a version which has not been correctly signed to control the trust chain for future updates. This is fixed in version 0.12 and newer."
				}
			],
			"affected": [
				{
					"vendor": "theupdateframework",
					"product": "tuf",
					"versions": [
						{
							"status": "affected",
							"version": "< 0.12"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "CWE",
							"lang": "en",
							"description": "CWE-863: Incorrect Authorization",
							"cweId": "CWE-863"
						}
					]
				}
			],
			"metrics": [
				{
					"cvssV3_1": {
						"version": "3.1",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:H/A:N",
						"attackVector": "NETWORK",
						"attackComplexity": "LOW",
						"privilegesRequired": "LOW",
						"userInteraction": "REQUIRED",
						"scope": "CHANGED",
						"confidentialityImpact": "HIGH",
						"integrityImpact": "HIGH",
						"availabilityImpact": "NONE",
						"baseScore": 8.7,
						"baseSeverity": "HIGH"
					}
				}
			],
			"references": [
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://github.com/theupdateframework/tuf/security/advisories/GHSA-f8mr-jv2c-v8mg"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://github.com/theupdateframework/tuf/pull/885"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://github.com/theupdateframework/tuf/releases/tag/v0.12.0"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://pypi.org/project/tuf"
				},
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://github.com/theupdateframework/tuf/commit/3d342e648fbacdf43a13d7ba8886aaaf07334af7"
				}
			],
			"source": {
				"advisory": "GHSA-f8mr-jv2c-v8mg",
				"discovery": "UNKNOWN"
			},
			"x_legacyV4Record": {
				"CVE_data_meta": {
					"ASSIGNER": "security-advisories@github.com",
					"ID": "CVE-2020-15163",
					"STATE": "PUBLIC",
					"TITLE": "Invalid root may become trusted root in The Update Framework (TUF)"
				},
				"affects": {
					"vendor": {
						"vendor_data": [
							{
								"product": {
									"product_data": [
										{
											"product_name": "tuf",
											"version": {
												"version_data": [
													{
														"version_value": "< 0.12"
													}
												]
											}
										}
									]
								},
								"vendor_name": "theupdateframework"
							}
						]
					}
				},
				"data_format": "MITRE",
				"data_type": "CVE",
				"data_version": "4.0",
				"description": {
					"description_data": [
						{
							"lang": "eng",
							"value": "Python TUF (The Update Framework) reference implementation before version 0.12 it will incorrectly trust a previously downloaded root metadata file which failed verification at download time. This allows an attacker who is able to serve multiple new versions of root metadata (i.e. by a person-in-the-middle attack) culminating in a version which has not been correctly signed to control the trust chain for future updates. This is fixed in version 0.12 and newer."
						}
					]
				},
				"impact": {
					"cvss": {
						"attackComplexity": "LOW",
						"attackVector": "NETWORK",
						"availabilityImpact": "NONE",
						"baseScore": 8.7,
						"baseSeverity": "HIGH",
						"confidentialityImpact": "HIGH",
						"integrityImpact": "HIGH",
						"privilegesRequired": "LOW",
						"scope": "CHANGED",
						"userInteraction": "REQUIRED",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:H/A:N",
						"version": "3.1"
					}
				},
				"problemtype": {
					"problemtype_data": [
						{
							"description": [
								{
									"lang": "eng",
									"value": "CWE-863: Incorrect Authorization"
								}
							]
						}
					]
				},
				"references": {
					"reference_data": [
						{
							"name": "https://github.com/theupdateframework/tuf/security/advisories/GHSA-f8mr-jv2c-v8mg",
							"refsource": "CONFIRM",
							"url": "https://github.com/theupdateframework/tuf/security/advisories/GHSA-f8mr-jv2c-v8mg"
						},
						{
							"name": "https://github.com/theupdateframework/tuf/pull/885",
							"refsource": "MISC",
							"url": "https://github.com/theupdateframework/tuf/pull/885"
						},
						{
							"name": "https://github.com/theupdateframework/tuf/releases/tag/v0.12.0",
							"refsource": "MISC",
							"url": "https://github.com/theupdateframework/tuf/releases/tag/v0.12.0"
						},
						{
							"name": "https://pypi.org/project/tuf",
							"refsource": "MISC",
							"url": "https://pypi.org/project/tuf"
						},
						{
							"name": "https://github.com/theupdateframework/tuf/commit/3d342e648fbacdf43a13d7ba8886aaaf07334af7",
							"refsource": "CONFIRM",
							"url": "https://github.com/theupdateframework/tuf/commit/3d342e648fbacdf43a13d7ba8886aaaf07334af7"
						}
					]
				},
				"source": {
					"advisory": "GHSA-f8mr-jv2c-v8mg",
					"discovery": "UNKNOWN"
				}
			}
		},
		"adp": [
			{
				"providerMetadata": {
					"orgID": "af854a3a-2127-422b-91ae-364da2661108",
					"shortName": "CVE",
					"dateUpdated": "2024-08-04T13:08:22.456Z"
				},
				"title": "CVE Program Container",
				"references": [
					{
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "https://github.com/theupdateframework/tuf/security/advisories/GHSA-f8mr-jv2c-v8mg"
					},
					{
						"tags": [
							"x_refsource_MISC",
							"x_transferred"
						],
						"url": "https://github.com/theupdateframework/tuf/pull/885"
					},
					{
						"tags": [
							"x_refsource_MISC",
							"x_transferred"
						],
						"url": "https://github.com/theupdateframework/tuf/releases/tag/v0.12.0"
					},
					{
						"tags": [
							"x_refsource_MISC",
							"x_transferred"
						],
						"url": "https://pypi.org/project/tuf"
					},
					{
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "https://github.com/theupdateframework/tuf/commit/3d342e648fbacdf43a13d7ba8886aaaf07334af7"
					}
				]
			}
		]
	}
}
