{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.0",
	"cveMetadata": {
		"assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
		"assignerShortName": "mitre",
		"cveId": "CVE-2022-47515",
		"datePublished": "2022-12-18T00:00:00",
		"dateReserved": "2022-12-18T00:00:00",
		"dateUpdated": "2022-12-18T00:00:00",
		"state": "PUBLISHED"
	},
	"containers": {
		"cna": {
			"affected": [
				{
					"product": "n/a",
					"vendor": "n/a",
					"versions": [
						{
							"status": "affected",
							"version": "n/a"
						}
					]
				}
			],
			"descriptions": [
				{
					"lang": "en",
					"value": "An issue was discovered in drachtio-server before 0.8.20. It allows remote attackers to cause a denial of service (daemon crash) via a long message in a TCP request that leads to std::length_error."
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"description": "n/a",
							"lang": "en",
							"type": "text"
						}
					]
				}
			],
			"providerMetadata": {
				"dateUpdated": "2022-12-18T00:00:00",
				"orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
				"shortName": "mitre"
			},
			"references": [
				{
					"url": "https://github.com/drachtio/drachtio-server/issues/245"
				},
				{
					"url": "https://github.com/drachtio/drachtio-server/commit/4cf9fe2c420b86c16442215d449d40be777c1911"
				}
			]
		}
	}
}
