{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.0",
	"cveMetadata": {
		"cveId": "CVE-2021-37654",
		"assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
		"assignerShortName": "GitHub_M",
		"state": "PUBLISHED",
		"datePublished": "2021-08-12T20:30:23",
		"dateUpdated": "2021-08-12T20:30:23",
		"dateReserved": "2021-07-29T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "a0819718-46f1-4df5-94e2-005712e83aaa",
				"shortName": "GitHub_M",
				"dateUpdated": "2021-08-12T20:30:23"
			},
			"title": "Heap OOB and CHECK fail in `ResourceGather` in TensorFlow",
			"descriptions": [
				{
					"lang": "en",
					"value": "TensorFlow is an end-to-end open source platform for machine learning. In affected versions an attacker can trigger a crash via a `CHECK`-fail in debug builds of TensorFlow using `tf.raw_ops.ResourceGather` or a read from outside the bounds of heap allocated data in the same API in a release build. The [implementation](https://github.com/tensorflow/tensorflow/blob/f24faa153ad31a4b51578f8181d3aaab77a1ddeb/tensorflow/core/kernels/resource_variable_ops.cc#L660-L668) does not check that the `batch_dims` value that the user supplies is less than the rank of the input tensor. Since the implementation uses several for loops over the dimensions of `tensor`, this results in reading data from outside the bounds of heap allocated buffer backing the tensor. We have patched the issue in GitHub commit bc9c546ce7015c57c2f15c168b3d9201de679a1d. The fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected and still in supported range."
				}
			],
			"affected": [
				{
					"vendor": "tensorflow",
					"product": "tensorflow",
					"versions": [
						{
							"status": "affected",
							"version": ">= 2.5.0, < 2.5.1"
						},
						{
							"status": "affected",
							"version": ">= 2.4.0, < 2.4.3"
						},
						{
							"status": "affected",
							"version": "< 2.3.4"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "CWE",
							"lang": "en",
							"description": "CWE-125: Out-of-bounds Read",
							"cweId": "CWE-125"
						}
					]
				}
			],
			"metrics": [
				{
					"cvssV3_1": {
						"version": "3.1",
						"vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:H",
						"attackVector": "LOCAL",
						"attackComplexity": "LOW",
						"privilegesRequired": "LOW",
						"userInteraction": "NONE",
						"scope": "UNCHANGED",
						"confidentialityImpact": "HIGH",
						"integrityImpact": "LOW",
						"availabilityImpact": "HIGH",
						"baseScore": 7.3,
						"baseSeverity": "HIGH"
					}
				}
			],
			"references": [
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-2r8p-fg3c-wcj4"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "https://github.com/tensorflow/tensorflow/commit/bc9c546ce7015c57c2f15c168b3d9201de679a1d"
				}
			],
			"source": {
				"advisory": "GHSA-2r8p-fg3c-wcj4",
				"discovery": "UNKNOWN"
			},
			"x_legacyV4Record": {
				"CVE_data_meta": {
					"ASSIGNER": "security-advisories@github.com",
					"ID": "CVE-2021-37654",
					"STATE": "PUBLIC",
					"TITLE": "Heap OOB and CHECK fail in `ResourceGather` in TensorFlow"
				},
				"affects": {
					"vendor": {
						"vendor_data": [
							{
								"product": {
									"product_data": [
										{
											"product_name": "tensorflow",
											"version": {
												"version_data": [
													{
														"version_value": ">= 2.5.0, < 2.5.1"
													},
													{
														"version_value": ">= 2.4.0, < 2.4.3"
													},
													{
														"version_value": "< 2.3.4"
													}
												]
											}
										}
									]
								},
								"vendor_name": "tensorflow"
							}
						]
					}
				},
				"data_format": "MITRE",
				"data_type": "CVE",
				"data_version": "4.0",
				"description": {
					"description_data": [
						{
							"lang": "eng",
							"value": "TensorFlow is an end-to-end open source platform for machine learning. In affected versions an attacker can trigger a crash via a `CHECK`-fail in debug builds of TensorFlow using `tf.raw_ops.ResourceGather` or a read from outside the bounds of heap allocated data in the same API in a release build. The [implementation](https://github.com/tensorflow/tensorflow/blob/f24faa153ad31a4b51578f8181d3aaab77a1ddeb/tensorflow/core/kernels/resource_variable_ops.cc#L660-L668) does not check that the `batch_dims` value that the user supplies is less than the rank of the input tensor. Since the implementation uses several for loops over the dimensions of `tensor`, this results in reading data from outside the bounds of heap allocated buffer backing the tensor. We have patched the issue in GitHub commit bc9c546ce7015c57c2f15c168b3d9201de679a1d. The fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected and still in supported range."
						}
					]
				},
				"impact": {
					"cvss": {
						"attackComplexity": "LOW",
						"attackVector": "LOCAL",
						"availabilityImpact": "HIGH",
						"baseScore": 7.3,
						"baseSeverity": "HIGH",
						"confidentialityImpact": "HIGH",
						"integrityImpact": "LOW",
						"privilegesRequired": "LOW",
						"scope": "UNCHANGED",
						"userInteraction": "NONE",
						"vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:H",
						"version": "3.1"
					}
				},
				"problemtype": {
					"problemtype_data": [
						{
							"description": [
								{
									"lang": "eng",
									"value": "CWE-125: Out-of-bounds Read"
								}
							]
						}
					]
				},
				"references": {
					"reference_data": [
						{
							"name": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-2r8p-fg3c-wcj4",
							"refsource": "CONFIRM",
							"url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-2r8p-fg3c-wcj4"
						},
						{
							"name": "https://github.com/tensorflow/tensorflow/commit/bc9c546ce7015c57c2f15c168b3d9201de679a1d",
							"refsource": "MISC",
							"url": "https://github.com/tensorflow/tensorflow/commit/bc9c546ce7015c57c2f15c168b3d9201de679a1d"
						}
					]
				},
				"source": {
					"advisory": "GHSA-2r8p-fg3c-wcj4",
					"discovery": "UNKNOWN"
				}
			}
		}
	}
}
