{
	"dataType": "CVE_RECORD",
	"dataVersion": "5.1",
	"cveMetadata": {
		"cveId": "CVE-2013-1629",
		"assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
		"assignerShortName": "mitre",
		"state": "PUBLISHED",
		"datePublished": "2022-10-03T16:14:49",
		"dateUpdated": "2024-08-06T15:04:49.544Z",
		"dateReserved": "2022-10-03T00:00:00"
	},
	"containers": {
		"cna": {
			"providerMetadata": {
				"orgID": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
				"shortName": "mitre",
				"dateUpdated": "2022-10-03T16:14:49"
			},
			"descriptions": [
				{
					"lang": "en",
					"value": "pip before 1.3 uses HTTP to retrieve packages from the PyPI repository, and does not perform integrity checks on package contents, which allows man-in-the-middle attackers to execute arbitrary code via a crafted response to a \"pip install\" operation."
				}
			],
			"affected": [
				{
					"vendor": "n/a",
					"product": "n/a",
					"versions": [
						{
							"status": "affected",
							"version": "n/a"
						}
					]
				}
			],
			"problemTypes": [
				{
					"descriptions": [
						{
							"type": "text",
							"lang": "en",
							"description": "n/a"
						}
					]
				}
			],
			"references": [
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "http://www.pip-installer.org/en/latest/installing.html"
				},
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://github.com/pypa/pip/issues/425"
				},
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "http://www.pip-installer.org/en/latest/news.html#changelog"
				},
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://github.com/pypa/pip/pull/791/files"
				},
				{
					"tags": [
						"x_refsource_CONFIRM"
					],
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=968059"
				},
				{
					"tags": [
						"x_refsource_MISC"
					],
					"url": "http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/"
				}
			],
			"x_legacyV4Record": {
				"CVE_data_meta": {
					"ASSIGNER": "cve@mitre.org",
					"ID": "CVE-2013-1629",
					"STATE": "PUBLIC"
				},
				"affects": {
					"vendor": {
						"vendor_data": [
							{
								"product": {
									"product_data": [
										{
											"product_name": "n/a",
											"version": {
												"version_data": [
													{
														"version_value": "n/a"
													}
												]
											}
										}
									]
								},
								"vendor_name": "n/a"
							}
						]
					}
				},
				"data_format": "MITRE",
				"data_type": "CVE",
				"data_version": "4.0",
				"description": {
					"description_data": [
						{
							"lang": "eng",
							"value": "pip before 1.3 uses HTTP to retrieve packages from the PyPI repository, and does not perform integrity checks on package contents, which allows man-in-the-middle attackers to execute arbitrary code via a crafted response to a \"pip install\" operation."
						}
					]
				},
				"problemtype": {
					"problemtype_data": [
						{
							"description": [
								{
									"lang": "eng",
									"value": "n/a"
								}
							]
						}
					]
				},
				"references": {
					"reference_data": [
						{
							"name": "http://www.pip-installer.org/en/latest/installing.html",
							"refsource": "CONFIRM",
							"url": "http://www.pip-installer.org/en/latest/installing.html"
						},
						{
							"name": "https://github.com/pypa/pip/issues/425",
							"refsource": "CONFIRM",
							"url": "https://github.com/pypa/pip/issues/425"
						},
						{
							"name": "http://www.pip-installer.org/en/latest/news.html#changelog",
							"refsource": "CONFIRM",
							"url": "http://www.pip-installer.org/en/latest/news.html#changelog"
						},
						{
							"name": "https://github.com/pypa/pip/pull/791/files",
							"refsource": "CONFIRM",
							"url": "https://github.com/pypa/pip/pull/791/files"
						},
						{
							"name": "https://bugzilla.redhat.com/show_bug.cgi?id=968059",
							"refsource": "CONFIRM",
							"url": "https://bugzilla.redhat.com/show_bug.cgi?id=968059"
						},
						{
							"name": "http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/",
							"refsource": "MISC",
							"url": "http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/"
						}
					]
				}
			}
		},
		"adp": [
			{
				"providerMetadata": {
					"orgID": "af854a3a-2127-422b-91ae-364da2661108",
					"shortName": "CVE",
					"dateUpdated": "2024-08-06T15:04:49.544Z"
				},
				"title": "CVE Program Container",
				"references": [
					{
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "http://www.pip-installer.org/en/latest/installing.html"
					},
					{
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "https://github.com/pypa/pip/issues/425"
					},
					{
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "http://www.pip-installer.org/en/latest/news.html#changelog"
					},
					{
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "https://github.com/pypa/pip/pull/791/files"
					},
					{
						"tags": [
							"x_refsource_CONFIRM",
							"x_transferred"
						],
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=968059"
					},
					{
						"tags": [
							"x_refsource_MISC",
							"x_transferred"
						],
						"url": "http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/"
					}
				]
			}
		]
	}
}
